### PR TITLE
Added check to return quietly if the path does not exist

### PR DESCRIPTION
**Pull request by Muhammadwasi**
- Added a check for the path existence. If it doesn't exist, it will return and exit quietly.

### CODE REVIEW

**Comment by mgrajesh1** [comment]
@Muhammadwasi , thanks for raising PR. Can I request a change to the code? Printing an error message to the console before exiting would be graceful.

Thanks
@mgrajesh1

**Comment by Muhammadwasi** [comment]
@mgrajesh1 sure. I will update the PR. Please specify the message.

**Comment by mgrajesh1** [comment]
@Muhammadwasi , how does 'Invalid path : <path>' sound?

**Comment by Muhammadwasi** [comment]
Yes. That will be good indication.

**Review by mgrajesh1 — COMMENTED** [review]
Looks good, thank you

**Review by mgrajesh1 — APPROVED** [review]

**Comment by Muhammadwasi** [comment]
@mgrajesh1 the merging is blocked due to commits to be signed. Can you please check?

**Comment by Muhammadwasi** [comment]
@mgrajesh1 can you please approve for workflow? I just updated GPG keys and signed my commits in this branch.

**Review by mgrajesh1 — APPROVED** [review]

**Comment by mgrajesh1** [comment]
@Muhammadwasi , congrats on your first contribution. Thank you.

**Pull request merged**
